package network.narrative.auction.domain;

import java.util.concurrent.atomic.AtomicBoolean;

public class Auction {

	private Integer id;

	private Item item;

	private Double currentBid;

	private User seller;

	private User highestBidder;

	private AtomicBoolean active = new AtomicBoolean(false);

	// TODO add bid history attribute

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Item getItem() {
		return item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Double getCurrentBid() {
		return currentBid;
	}

	public void setCurrentBid(Double currentBid) {
		this.currentBid = currentBid;
	}

	public User getSeller() {
		return seller;
	}

	public void setSeller(User seller) {
		this.seller = seller;
	}

	public User getHighestBidder() {
		return highestBidder;
	}

	public void setHighestBidder(User highestBidder) {
		this.highestBidder = highestBidder;
	}

	public String getHighestBidderName() {
		return highestBidder == null ? "none" : highestBidder.toString();
	}

	public Boolean isActive() {
		return active.get();
	}

	/* needed by Spring MVC as it won't find "is" prefixed getter */
	public Boolean getActive() {
		return active.get();
	}

	public void setActive(Boolean active) {
		this.active.set(active);
	}

	/* for sake of time, this was generated by Eclipse, so please don't judge as my style!  :) */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/* for sake of time, this was generated by Eclipse, so please don't judge as my style!  :) */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Auction other = (Auction) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		String s = "Auction [id=" + id
				+ ", item=" + item.getDescription()
				+ ", currentBid=" + currentBid
				+ ", seller=" + seller.getName()
				+ ", highestBidder=" + (highestBidder == null ? "none" : highestBidder.toString())
				+ ", active=" + active + "]";
		
		return s;
	}

}
